//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BykesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwByke
    {
        public int BykeId { get; set; }
        public string BykeDescription { get; set; }
        public int VendorID { get; set; }
        public string BykeType { get; set; }
        public string Status { get; set; }
    }
}
